#!/bin/bash

# Cambia la plantilla de latex al directorio donde esté
utils/expande-URLs.py 
pandoc --template="$PWD"/utils/plantilla.latex \
    -V lang=es-ES \
    -V author='JJ Merelo' -V title='Playa Granada: Arquitectura e Historia'\
    -V documentclass=book\
    --pdf-engine=xelatex \
    -o playa-granada-kdp.pdf \
    intro-links.md  pois/pueblo-del-chirimoyo-links.md\
    pois/terrazas-playa-granada-links.md pois/villa-astrida-links.md\
    pois/viviendas-varias-links.md  pois/Oleaje-links.md\
    pois/iglesia-josefina-bakhita-links.md\
    pois/arquitectura-tradicional.md pois/tras-la-pandemia.md --toc
rm *-links.md pois/*-links.md


