#!/bin/bash

# Cambia la plantilla de latex al directorio donde esté
utils/elimina-URLs.py
pandoc --template="$PWD"/utils/plantilla.latex \
    -V lang=es-ES \
    -V author='JJ Merelo' -V title='Playa Granada: Arquitectura e Historia'\
    -V documentclass=book\
    --pdf-engine=xelatex \
    -o playa-granada-kdp.pdf \
    intro-nolinks.md  pois/pueblo-del-chirimoyo-nolinks.md\
    pois/terrazas-playa-granada-nolinks.md pois/villa-astrida-nolinks.md\
    pois/viviendas-varias-nolinks.md  pois/Oleaje-nolinks.md\
    pois/iglesia-josefina-bakhita-nolinks.md\
    pois/vertice-geodesico-nolinks.md\
    pois/el-piruli-nolinks.md\
    pois/arquitectura-tradicional.md pois/tras-la-pandemia.md --toc
rm *-nolinks.md pois/*-nolinks.md


