#!/bin/bash



pandoc --toc --epub-metadata=metadata.xml --css=playa-granada.css \
    --metadata title="Playa Granada, historia y arquitectura" \
    -o playa-granada.epub playa-granada.txt \
    intro.md pois/pueblo-del-chirimoyo.md\
    pois/terrazas-playa-granada.md pois/villa-astrida.md\
    pois/viviendas-varias.md pois/Oleaje.md\
    pois/iglesia-josefina-bakhita.md



