name: "Comprueba texto"

on:
  push:
    paths:
      - '**/*.md'
      - '**/words.dic'

  pull_request:
    paths:
      - '**/*.md'
      - '**/words.dic'

jobs:
  OrtografiaMD:
    runs-on: ubuntu-latest

    steps:
      - name: Prerrequisites
        run: |
          sudo apt-mark hold grub-efi-amd64-signed && sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y libtext-hunspell-perl autopoint
      - uses: actions/checkout@v4
      - name: Usa install-with-cpm
        uses: perl-actions/install-with-cpm@v1
        with:
          install: |
            Test::Text
            TAP::Harness
          sudo: true
      - name: Comprueba la ortografía
        run: |
          curl https://raw.githubusercontent.com/JJ/Test-Text/master/data/Spanish.aff -o Spanish.aff
          curl https://raw.githubusercontent.com/SublimeText/Dictionaries/master/Spanish.dic -o Spanish.dic
          perl -MTAP::Harness -e 'use utf8; my $harness = TAP::Harness->new( { verbosity => 0} ); die "FAIL" if $harness->runtests( "just_check.t" )->failed;'
